### ISSUE TITLE
Urgent issue - Unable to add new films to the DB - Neelakurinji

### ISSUE THREAD

**Issue by Kiranz-m3db** [kevinsiji/m3db#45] opened 2015-08-11 18:42 UTC
Error shows the below

The website encountered an unexpected error. Please try again later.

**Comment by rakeshkonni** [comment] 2015-08-12 05:23
Duplicate of #43

**Comment by rakeshkonni** [comment] 2015-08-12 05:25
@kevinsiji This is a major issue.

**Comment by kevinsiji** [comment] 2015-08-12 05:43
Duplicate of #43

**Closed as completed by kevinsiji** 2015-08-12 05:43 UTC
Labels: duplicate
