### ISSUE TITLE
Website encountered an unexpected error while creating new films with very basic details

### ISSUE THREAD

**Issue by Kiranz-m3db** [kevinsiji/m3db#55] opened 2015-08-19 02:24 UTC
Serious issue since we are not able to add any new films with even very few details :( - Kindly add it as an urgent P0 case.

![image](https://cloud.githubusercontent.com/assets/13637422/9347465/7faa83de-4632-11e5-8088-870d49b9b491.png)

**Comment by kevinsiji** [comment] 2015-08-19 04:35
I will try to complete fixing this today. Its a long process, each field have to be fixed. :(

**Comment by kevinsiji** [comment] 2015-08-19 15:17
Duplicate of Issue #43

**Closed as completed by kevinsiji** 2015-08-19 15:17 UTC
Labels: duplicate
