### ISSUE TITLE
Unable to reference newly added artist on Lyrics

### ISSUE THREAD

**Issue by Kiranz-m3db** [kevinsiji/m3db#60] opened 2015-08-22 03:41 UTC
Unable to call or reference newly added artists into the lyrics but they can be added to movies..!

see the lyrics edit

![image](https://cloud.githubusercontent.com/assets/13637422/9422350/abd142a0-4898-11e5-84e1-de757e1591bd.png)

and see the movie edit its showing
![image](https://cloud.githubusercontent.com/assets/13637422/9422351/c3de848e-4898-11e5-8fba-620a1dff745d.png)

**Comment by kevinsiji** [comment] 2015-08-22 05:01
Duplicate of #59

**Closed as completed by kevinsiji** 2015-08-22 05:01 UTC
Labels: duplicate
